"""The tools carry selftests, and something has to run them.

A selftest nothing invokes is the same defect one level out: it would pass, and
nobody could say whether it was capable of failing. `pytest` is this repository's
gate, so the gate runs it.

armory's house standard goes further — `mutation_check.sh` breaks each tool at a
named line and requires the matching selftest to flip red. This is the local
half: the selftest runs on every push, and the second test below restores the
original defect and requires the selftest to catch it.
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"

WIDE = r'''r"font-size\s*[:=]\s*[\"']?\s*([\d.]+)\s*(px|pt|pc|mm|cm|in|em|rem|%)?",'''
NARROW = r'''r"font-size\s*[:]\s*([\d.]+)\s*(px)",'''


def test_measure_type_selftest_passes():
    r = subprocess.run([sys.executable, str(TOOLS / "measure_type.py"), "--selftest"],
                       capture_output=True, text=True)
    assert r.returncode == 0, (
        "tools/measure_type.py --selftest failed:\n" + r.stdout + r.stderr)


def test_measure_type_selftest_can_fail():
    """THE ONLY VERSION OF THIS TEST THAT MEANS ANYTHING.

    The tool's first pattern read `font-size:7px` and was blind to SVG's own
    `font-size="7"` — and then reported `ok`, so a figure whose every label was
    3pt passed silently. draughtsman happens to emit the CSS form, so the
    selftest was green on the only producer it had ever seen. Found by
    murderboard-7a pointing it at a file this repository did not write.

    So the narrow pattern is restored here and the selftest is required to go
    red, on that case by name. Without this, the test above is decoration.
    """
    src = (TOOLS / "measure_type.py").read_text(encoding="utf-8")
    assert WIDE in src, (
        "the size pattern has moved; this mutation no longer reproduces the "
        "defect it guards, so it is not guarding anything")
    with tempfile.TemporaryDirectory() as td:
        broken = Path(td) / "broken.py"
        broken.write_text(src.replace(WIDE, NARROW, 1), encoding="utf-8")
        r = subprocess.run([sys.executable, str(broken), "--selftest"],
                           capture_output=True, text=True)
    assert r.returncode != 0, (
        "with the narrow pattern restored the selftest still passed, so it does "
        "not test what it claims to")
    assert "presentation attribute" in r.stdout, (
        "the selftest failed, but not on the attribute-form case:\n" + r.stdout)


# --- tools/compare_stack.py, which draws a claim about a grouping ------------

def test_compare_stack_selftest_passes():
    r = subprocess.run([sys.executable, str(TOOLS / "compare_stack.py"), "--selftest"],
                       capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0, (
        "tools/compare_stack.py --selftest failed:\n" + r.stdout + r.stderr)


def test_compare_stack_selftest_sees_a_stage_it_no_longer_covers():
    """THE DRIFT THIS EXISTS FOR, REPRODUCED.

    `compare.svg` is generated by hand — it needs torchview, which nothing here
    installs — and committed. So the drawing cannot rot, but the DECLARATION can:
    rename or split a stage in `whisper/spec.json`, and the tool still names the
    old one over a figure that still shows it. Correct-looking, and about a
    grouping that no longer exists, which is the failure this repository is named
    for arriving in its own comparison of it.

    The mutation renames one stage in a copy of the figure the tool reads its
    labels from, and the selftest is required to notice.
    """
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        (tmp / "tools").mkdir()
        (tmp / "examples" / "gallery" / "whisper").mkdir(parents=True)
        (tmp / "tools" / "compare_stack.py").write_text(
            (TOOLS / "compare_stack.py").read_text(encoding="utf-8"), encoding="utf-8")
        whisper = ROOT / "examples" / "gallery" / "whisper"
        (tmp / "examples/gallery/whisper/figure.svg").write_text(
            (whisper / "figure.svg").read_text(encoding="utf-8")
            .replace('data-stage="dff"', 'data-stage="dff2"', 1), encoding="utf-8")
        (tmp / "examples/gallery/whisper/compare.svg").write_text(
            (whisper / "compare.svg").read_text(encoding="utf-8"), encoding="utf-8")
        r = subprocess.run([sys.executable, str(tmp / "tools" / "compare_stack.py"),
                            "--selftest"], capture_output=True, text=True)
    assert r.returncode != 0, (
        "a stage renamed out from under the assignment left the selftest green, "
        "so it does not check the declaration it claims to:\n" + r.stdout)
    assert "figure.svg draws" in r.stdout, (
        "the selftest failed, but not on the renamed stage:\n" + r.stdout)


def test_compare_stack_selftest_sees_two_regions_over_each_other():
    """THE DEFECT THIS CHECK WAS WRITTEN FOR, REPRODUCED.

    Two regions overlapped by 5.0 x 65.7 units in the committed figure and
    nothing here saw it: a region is a rectangle drawn behind the graph, and the
    only geometry check this repository had asks whether an EDGE's path runs
    through a stage box. Box against box was nobody's question. It was found by
    the person the figure is for, on a phone, zoomed in.

    The cause was a fixed 3-unit pad on each side closing a gap of about one unit
    between the encoder's nodes and the first decoder block's. The pad is capped
    at the room available now, and this asserts the checker would fail if it
    stopped being.
    """
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        (tmp / "tools").mkdir()
        (tmp / "examples" / "gallery" / "whisper").mkdir(parents=True)
        (tmp / "tools" / "compare_stack.py").write_text(
            (TOOLS / "compare_stack.py").read_text(encoding="utf-8"), encoding="utf-8")
        whisper = ROOT / "examples" / "gallery" / "whisper"
        (tmp / "examples/gallery/whisper/figure.svg").write_text(
            (whisper / "figure.svg").read_text(encoding="utf-8"), encoding="utf-8")
        svg = (whisper / "compare.svg").read_text(encoding="utf-8")
        m = re.search(r'<rect class="ds-region" data-stage="dself" x="([-\d.]+)"', svg)
        assert m, "the committed figure no longer names its regions"
        slid = svg.replace(m.group(0), m.group(0).replace(
            m.group(1), f"{float(m.group(1)) - 40:.2f}"))
        (tmp / "examples/gallery/whisper/compare.svg").write_text(slid, encoding="utf-8")
        r = subprocess.run([sys.executable, str(tmp / "tools" / "compare_stack.py"),
                            "--selftest"], capture_output=True, text=True)
    assert r.returncode != 0, (
        "a region slid 40 units into its neighbour and the selftest stayed green, "
        "so it is not checking the geometry it claims to:\n" + r.stdout)
    assert "overlap" in r.stdout, (
        "the selftest failed, but not on the overlap:\n" + r.stdout)
